------------------------------------------------------국가


INSERT INTO Country VALUES (Country_seq.nextVal, '한국');
INSERT INTO Country VALUES (Country_seq.nextVal, '미국');
INSERT INTO Country VALUES (Country_seq.nextVal, '일본');
INSERT INTO Country VALUES (Country_seq.nextVal, '프랑스');
INSERT INTO Country VALUES (Country_seq.nextVal, '중국');
INSERT INTO Country VALUES (Country_seq.nextVal, '뉴질랜드');
INSERT INTO Country VALUES (Country_seq.nextVal, '영국');
INSERT INTO Country VALUES (Country_seq.nextVal, '홍콩');

-------------------------------------------------------------장르

INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '멜로');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '로맨스');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '드라마');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '액션');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '모험');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, 'SF');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '범죄');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '애니메이션');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '코미디');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '판타지');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '스릴러');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '미스터리');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '시대극');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '역사');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '서사');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '공포');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '어드벤처');
INSERT INTO GENRE VALUES (GENRE_SEQ.nextVal, '다큐멘터리');

--------------------------------------------------------------영화

-- 1. 만약에 우리
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '만약에 우리', 'Once We Were Us', TO_DATE('2025-12-31', 'YYYY-MM-DD'), 120, 2142504, 1, 3, 1);

-- 2. 신의악단
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '신의악단', 'Choir of God', TO_DATE('2025-12-31', 'YYYY-MM-DD'), 110, 785699, 1, 3, 2);

-- 3. 아바타: 불과 재
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '아바타: 불과 재', 'Avatar: Fire and Ash', TO_DATE('2025-12-17', 'YYYY-MM-DD'), 192, 6612934, 2, 2, 3);

-- 4. 프로젝트 Y
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '프로젝트 Y', 'PROJECT Y', TO_DATE('2026-01-21', 'YYYY-MM-DD'), 115, 124663, 1, 3, 4); --4

-- 5. 신비아파트 10주년 극장판: 한 번 더, 소환
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '신비아파트 10주년 극장판: 한 번 더, 소환', 'Shinbi''s Haunted House: One More Summon', TO_DATE('2026-01-14', 'YYYY-MM-DD'), 85, 259605, 1, 1, 5);

-- 6. 주토피아 2
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '주토피아 2', 'Zootopia 2', TO_DATE('2025-11-26', 'YYYY-MM-DD'), 105, 8539371, 2, 1, 6);

-- 7. 하트맨
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '하트맨', 'Heartman: Rock and Love', TO_DATE('2026-01-14', 'YYYY-MM-DD'), 95, 239172, 1, 2, 7);

-- 8. 천공의 성 라퓨타
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '천공의 성 라퓨타', 'Laputa: Castle in the Sky', TO_DATE('2004-04-30', 'YYYY-MM-DD'), 124, 107936, 3, 1, 8); ---8

-- 9. 시라트
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '시라트', 'Sirat', TO_DATE('2026-01-21', 'YYYY-MM-DD'), 115, 34851, 4, 3, 9);

-- 10. 직장상사 길들이기
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '직장상사 길들이기', 'Send Help', TO_DATE('2026-01-28', 'YYYY-MM-DD'), 100, 21385, 2, 3, 10);

-- 11. 이터널 선샤인
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '이터널 선샤인', 'Eternal Sunshine of the Spotless Mind', TO_DATE('2005-11-10', 'YYYY-MM-DD'), 107, 71480, 2, 3, 11);

-- 12. 시스터
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '시스터', 'SISTER', TO_DATE('2026-01-28', 'YYYY-MM-DD'), 105, 18183, 1, 3, 12); ---12

-- 13. 하우스메이드
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '하우스메이드', 'The Housemaid', TO_DATE('2026-01-28', 'YYYY-MM-DD'), 100, 18040, 2, 4, 13);

-- 14. 왕과 사는 남자
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '왕과 사는 남자', 'The King''s Warden', TO_DATE('2026-02-04', 'YYYY-MM-DD'), 115, 19442, 1, 2, 14);

-- 15. 731
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '731', '731', TO_DATE('2026-01-01', 'YYYY-MM-DD'), 110, 28421, 5, 3, 15);

-- 16. 프라이메이트
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '프라이메이트', 'Primate', TO_DATE('2026-01-28', 'YYYY-MM-DD'), 95, 14184, 2, 4, 16);

-- 17. 고고다이노 극장판: 곤충세계 대모험
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '고고다이노 극장판: 곤충세계 대모험', 'GoGo Dino the Movie', TO_DATE('2026-01-14', 'YYYY-MM-DD'), 65, 35017, 1, 1, 17);

-- 18. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 (2025)
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '오늘 밤, 세계에서 이 사랑이 사라진다 해도 (2025)', 'Even If This Love Disappears...', TO_DATE('2025-12-24', 'YYYY-MM-DD'), 105, 858824, 1, 2, 18);

-- 19. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 (2022)
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '오늘 밤, 세계에서 이 사랑이 사라진다 해도 (2022)', 'Even If This Love Disappears...', TO_DATE('2022-11-30', 'YYYY-MM-DD'), 121, 1150897, 3, 2, 19);

-- 20. 슈가
INSERT INTO MOVIE (MOVIE_SEQ, TITLE_KOR, TITLE_ENG, REGDATE, TIME, AUDIENCE_COUNT, COUNTRY_SEQ, RAITING_SEQ, SYNOPSIS_SEQ) 
VALUES (MOVIE_SEQ.nextVal, '슈가', 'SUGAR', TO_DATE('2026-01-21', 'YYYY-MM-DD'), 105, 15014, 1, 1, 20);




---------------------- 심의 등급

INSERT INTO (RATING_SEQ, RATING_NAME) VALUES (1, '전체 관람가');
INSERT INTO (RATING_SEQ, RATING_NAME) VALUES (2, '12세이상관람가');
INSERT INTO (RATING_SEQ, RATING_NAME) VALUES (3, '15세이상관람가');
INSERT INTO (RATING_SEQ, RATING_NAME) VALUES (4, '청소년 관람불가');



----------------------------------------- 배우 / -- ACTOR (배우) DML

INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (1, '배우', '구교환', DATE '1982-12-14', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (2, '배우', '문가영', DATE '1996-07-10', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (3, '배우', '신정근', DATE '1966-09-26', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (4, '배우', '박시후', DATE '1978-04-03', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (5, '배우', '정진운', DATE '1991-05-02', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (6, '배우', '태항호', DATE '1983-07-22', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (7, '배우', '샘 워싱턴', DATE '1976-08-02', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (8, '배우', '조 샐다나', DATE '1978-06-19', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (9, '배우', '시고니 위버', DATE '1949-10-08', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (10, '배우', '한소희', DATE '1994-11-18', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (11, '배우', '전종서', DATE '1994-07-05', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, GENDER) VALUES (12, '배우', '김신록', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (13, '성우', '김영은', DATE '1984-05-30', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (14, '성우', '조현정', DATE '1978-07-25', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (15, '성우', '신용우', DATE '1976-03-19', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (16, '배우', '지니퍼 굿윈', DATE '1978-05-22', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (17, '배우', '제이슨 베이트먼', DATE '1969-01-14', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (18, '배우', '키 호이 콴', DATE '1971-08-20', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (19, '배우', '권상우', DATE '1976-08-08', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (20, '배우', '문채원', DATE '1986-11-13', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, GENDER) VALUES (21, '배우', '김서현', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (22, '성우', '타나카 마유미', DATE '1955-01-15', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (23, '배우', '세르지 로페즈', DATE '1965-12-22', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (24, '배우', '레이첼 맥아담스', DATE '1978-11-17', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (25, '배우', '딜런 오브라이언', DATE '1991-08-26', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (26, '배우', '짐 캐리', DATE '1962-01-07', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (27, '배우', '케이트 윈슬렛', DATE '1975-10-15', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (28, '배우', '커스틴 던스트', DATE '1982-04-30', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (29, '배우', '정지소', DATE '1999-09-17', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (30, '배우', '이수혁', DATE '1988-05-31', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (31, '배우', '차주영', DATE '1990-06-05', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (32, '배우', '시드니 스위니', DATE '1997-09-12', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (33, '배우', '아만다 사이프리드', DATE '1985-12-03', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (34, '배우', '브랜든 스클레너', DATE '1990-06-26', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (35, '배우', '유해진', DATE '1970-01-04', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (36, '배우', '박지훈', DATE '1999-05-29', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (37, '배우', '유지태', DATE '1976-04-13', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (38, '배우', '우 지앙', DATE '1967-11-14', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (39, '배우', '왕 지웬', DATE '1966-06-25', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (40, '배우', '나이웬 리', DATE '1974-10-18', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (41, '배우', '조니 시쿼야', DATE '2002-10-25', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, GENDER) VALUES (42, '배우', '지아 헌터', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, GENDER) VALUES (43, '배우', '트로이 코처', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (44, '배우', '추영우', DATE '1999-06-05', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (45, '배우', '신시아', DATE '1999-05-12', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (46, '배우', '조유정', DATE '1999-09-17', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (47, '배우', '미치에다 슌스케', DATE '2002-07-25', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (48, '배우', '후쿠모토 리코', DATE '2000-11-25', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (49, '배우', '후루카와 코도네', DATE '1996-10-25', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (50, '배우', '최지우', DATE '1975-06-11', 2);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (51, '배우', '민진웅', DATE '1986-08-22', 1);
INSERT INTO (ACTOR_SEQ, JOB, NAME, BIRTH, GENDER) VALUES (52, '배우', '고동하', DATE '2012-06-14', 1);